language: node_js
deploy:
  provider: pages
  skip-cleanup: true
  github-token: GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
secure: "xBAX6j6v1/UBW/ODWexVvnNVGX31Bi3DpdNv0wq/kVnrhTlwy04Dr0dPhiTc55GvA7P0mFxKuJa5cyfZNfbKBbXhishIajKuEawSgzfX0ftRT5pUqXvD25Tq3lyn0d4IYO8DxYoXjdIttf6R7imMggcXKlKRugJpksdvgBGUCfeMb3Q+NdgAAPfdUqvGwIthw9Z0F6DgfT6DKCttMUpLFsEjnzVA2kCRv1uNcH1JfkeaUKcqDZ67XdjbBNFeeomKGe+gW3UmTh3ioAfqcCKvHeIkZ9Gpjrva7vlLB6ufmhcVyeWGWrGQFhNCp4zhXOgD9McdXTZ7aYC9Ii6d3p348HamX7vC28lgMfvF3IBmWsbCv6FdDf784g+10JiTkXvydK+EUyrhfv0K9648znKEnsj/gTaQ/rpKZ1CDcx71cH+Pnpe8Y+y1APllu8Yml0Ib2+wQxN9aLpLPA8xYxXU1KVlyNjku4s1F6ZoHKbvx7nd94od1g7SRvaY0W74zLizz0uAE0L5I2vSVo78da8+75YLrfrg0ULuSdyjVslzS5lJ5FuqkbLIbD4tVBPj2OD723Wo34rEHT2fv1Z50XO6xfuYc+P4YLmcuGvF0hhrd1S/skYukKkHI+5oiZd9DxVwxUuNLAWsWzkv+yjEig/AtOkiCGT/zK5yTRvETo3UROIM="
